# Generated by Django 3.2.6 on 2021-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_regular_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_feature',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
